version: '3'

services:
    nginx:
        container_name: nginx_${APP_NAME}
        image: stenfrank/nginx:1.3
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/sites-available:/etc/nginx/sites-available
        networks:
            - network
        depends_on:
            - php
    php:
        container_name: php_${APP_NAME}
        restart: unless-stopped
        user: "${APP_USER}"
        build:
            context: ./docker/php/
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - network
        depends_on:
            - database

    database:
        container_name: database_${APP_NAME}
        image: mysql:5.7
        restart: unless-stopped
        volumes:
            - ./docker/mysql:/etc/mysql/conf.d
            - volumedata:/var/lib/mysql
        command: --max_allowed_packet=268435456
        ports:
            - "${APP_DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: ${APP_NAME}_user
            MYSQL_DATABASE: ${APP_NAME}_db
            MYSQL_PASSWORD: secret
        networks:
            - network

    phpmyadmin:
        container_name: phpmyadmin_${APP_NAME}
        depends_on:
            - database
        image: phpmyadmin
        restart: unless-stopped
        ports:
            - "${APP_PHPMYADMIN_PORT}:80"
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: password
            PMA_ABSOLUTE_URI: http://phpmyadmin/phpmyadmin/
        networks:
            - network

networks:
    network:
        name: ${APP_NAME}_network
        driver: "bridge"

volumes:
    volumedata:
        name: ${APP_NAME}_data
